version: '3'
services:
    node:
        build: ./build/node/
        volumes:
          - ./node:/app
        env_file:
          - ./build/node/.env    
        ports: 
          - '3000:3000'
        tty: true
        init: true   


